#!/bin/bash
# vLLM Server Startup Script
# Generated by VLLM GUI
# Model: /mnt/i/AI-Chat/models/minimax/MiniMax-M2.5-NVFP4
# Created: 2026/2/14 18:51:08

# Set environment variables
export CUDA_VISIBLE_DEVICES=0,1
# Use conda environment's python directly - no need for conda activate
source ~/miniconda3/etc/profile.d/conda.sh 2>/dev/null || true
PYTHON_PATH=~/miniconda3/envs/vllm/bin/python

# Start vLLM server
echo "Starting vLLM server..."
echo "Model: /mnt/i/AI-Chat/models/minimax/MiniMax-M2.5-NVFP4"
echo "Port: 8005"
echo "Tensor Parallel: 2"
$PYTHON_PATH -m vllm.entrypoints.openai.api_server --model "/mnt/i/AI-Chat/models/minimax/MiniMax-M2.5-NVFP4" --host 0.0.0.0 --port 8005 --tensor-parallel-size 2 --gpu-memory-utilization=0.9 --max-num-seqs 256 --quantization nvfp4 --max-model-len 128000 --served-model-name VLLM-MODEL --chat-template "/mnt/i/AI-Chat/models/minimax/MiniMax-M2.5-NVFP4/chat_template.jinja" --trust-remote-code --enable_expert_parallel --enable-auto-tool-choice --tool-call-parser minimax_m2 --reasoning-parser minimax_m2_append_think --compilation_config.cudagraph_mode=PIECEWISE
